- .gitignore
- _scripts/install_all.sh
- _scripts/syncserver.ini
- _scripts/syncserver.sh
- _scripts/update_all.sh
- servers.json
This fixes #4 in the simplest possible way, just making it a direct entry in servers.json.  I'm happy to iterate on this to e.g. put it in an extras.json if you prefer, just wanted to share my (apparently working!) config in the meantime.
> Add local syncserver instance.

- servers.json
> fix(content-server): set up NODE_ENV to development

- _scripts/install_all.sh
- _scripts/update_all.sh
- servers.json
Depends on https://github.com/mozilla/fxa-basket-proxy/pull/2
> feat(basket): use stand-alone fxa-basket-proxy repo.

- _scripts/install_all.sh
- _scripts/update_all.sh
- servers.json
Reverts mozilla/fxa-local-dev#32
> Revert "feat(basket): use stand-alone fxa-basket-proxy repo."

- _scripts/profile.js
> Use stage tokenserver for FXA_ENV=stage

- README.md
- package.json
- servers_extra.json
> chore(docs): Add docs for running Hello Service

- package.json
> fix(deps): Update to latest pm2

- test/lib/start-selenium.js
> fix(test): Update Selenium version to 2.53.0

- package.json
https://github.com/Unitech/pm2/blob/master/CHANGELOG.md#223
> fix(deps): update to pm2@2.2.3

- _scripts/install_all.sh
- servers.json
Fixes #84.
@mozilla/fxa-devs r?
> fix(servers): run the auth mailer inside fxa-auth-server

- _scripts/redis.js
- _scripts/redis.sh
- package.json
- servers.json
- test/curl.sh
npm start / pm2 start servers.json will start redis now.
> feat(redis): start redis on server start

- README.md
- _scripts/memcached.js
- servers.json
- test/curl.sh
> chore(server): #94 Added memcached service

- _scripts/start-android.js
Fixes https://github.com/mozilla/fxa-oauth-server/issues/545
> fix(oauth): Fix the oauth path to the server

- .travis.yml
- README.md
- _scripts/check.sh
- _scripts/check_node_version.js
- _scripts/install_all.sh
- _scripts/memcached.js
- _scripts/memcached.sh
- _scripts/redis.js
- mysql_servers.json
- package.json
- servers.json
@vladikoff , i started with checking memcached. 
It is failing if we install from source in mac.
t/lru-maintainer.t        (Wstat: 512 Tests: 226 Failed: 2)
do we need to proceed like this only ?
> #101 Create a script that alerts devs

- .travis.yml
- _scripts/install_all.sh
- _scripts/syncserver.sh
- servers.json
> fix(syncserver): Configure syncserver to use localhost verifier.

- .travis.yml
- README.md
- _scripts/check.sh
- _scripts/install_all.sh
- _scripts/update_all.sh
- servers.json
Fixes #111 
r? @vladikoff 
Question: Should we turn off rocket logs for `dev` too? They kinda get in the way, in my opinion.
> feat(install): add fxa-email-server to servers

- _scripts/install_all.sh
Fixes https://github.com/mozilla/fxa-local-dev/issues/121
> fix(install): link db mysql on install

- package.json
> fix(deps): Update deps, including lodash which has a sec vulnerability

- _scripts/channelserver.sh
- _scripts/install_all.sh
- _scripts/update_all.sh
- mysql_servers.json
- servers.json
- test/curl.sh
> Add channelserver

- _scripts/create_mysql.js
- _scripts/install_all.sh
- _scripts/oauth_mysql.sh
- mysql_servers.json
- servers.json
Connects to https://github.com/mozilla/fxa-auth-server/issues/2679
@mozilla/fxa-devs r?
> fix(config): update to use oauth server in auth directory

- _scripts/update_all.sh
> fix(update): update script to use npm ci

- README.md
> Update Link for npm-shrinkwrap.json files in Readme
