_scripts/install_all.sh, servers.json
This fixes an issue where, because `config.json` had been locally modified, a `git pull origin master` would refuse to continue, thus getting no update. This is a simpler way. (Depends on https://github.com/mozilla/123done/pull/137)
@vladikoff r?
=> fix(123done): don't overwrite config.json; set $CONFIG_123DONE=./config-local.json

_scripts/install_all.sh, _scripts/postinstall.sh
This make it a bit easier to debug problems the first time you try to install.
The bash flag`e` causes the script to abort on the first error and `x` prints the command so its easier to see what's running. With `e` its better to not use `&&` so I switched them to `;`
=> halt initial install on first error

README.md
These  are based on me coming to the readme with a fresh pair of eyes. The information was all there but it was packed quite densely and not always in chronological order, which made things easy to miss.
To give you some context, here's my reasoning behind each change:
* Initially I didn't realise the first bullet was  a separate step. I thought it was just explanation for `npm install`. Hence making them all numbered bullets and then clarifying `Manually install...`.
* I don't use bash as my shell, so it was a bit annoying not being able to just copy/paste the `&&`ed commands. Hence splitting them across lines so they work for everyone.
* Added hierarchy to the pm2 bullets so its clear what belongs to what.
* Gave an explicit heading to the troubleshooting section, so that it's easier to …
=> Improve readme for newcomers

_scripts/profile.js
The oauth-server thinks its publicUrl is `127.0.0.1`, and checks for this in browserid assertions.  The config value in the browser must match, or it get "invalid audience" errors when generating oauth tokens.
=> fix(oauth): configure browser with what oauth server thinks is its public url

_scripts/install_all.sh, _scripts/update_all.sh, servers.json
The fxa-basket-proxy repo change have landed, this change is now ready to go.  @vladikoff r?
Fixes #35.
=> feat(basket): use stand-alone fxa-basket-proxy repo.

_scripts/profile.js
The whole `npm start` flow to spin up a temporary profile here is quite nice even with the production servers, this adds ability to ask for that explicitly.
=> feat(profile): add a "prod" profile for using a fresh profile with prod servers

_scripts/profile.js
* With Fx45, the context should be fx_desktop_v2.
* Add context/service query params for settings.
@vladikoff - I'm not sure when this should land. With Fx 45, context has been updated to fx_desktop_v2, and the tentative fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1234165 adds the context/service query parameters for the /settings page.
=> fix(profile): Update context to use fx_desktop_v2.

.gitignore, Vagrantfile, _scripts/vagrant_provision.sh, local_config.yaml.example, servers.json
The following sections explains what changed and the reason. The Windows section explains the steps to get the machine working on windows and is here just for reference.
**Vagrantfile**
This file has been improved with the following changes:
1. Load configuration file (yaml) if exists.
2. Updated the format of box dependency declaration.
3. Memory and IP can be defined externally (in yaml file).
4. The atlas push must be configured in the external file.
**vagrant_provision.sh**
This file contains the steps required to build a working development environment.
**local_config.yaml.example**
This file should be duplicated and renamed to 'local_config.yaml' when overriding some configurations.
**servers.json**
Changed to not use the symlink when starting grunt (see windows host section). …
=> feat(vagrant): add provision script and improve current vagrantfile

_scripts/install_all.sh
Solves issue with fxa-auth-mailer which didn't run correctly after installation with:
cd fxa-local-dev
npm i
=> Add install fxa-auth-mailer to install_all.sh

servers.json
Hi @vladikoff!
I tried to setup fxa-oauth-console yesterday and I've noticed this error:
http://storage2.static.itmages.com/i/16/0706/h_1467844576_1587389_c7b03c0b11.png
After a small digging I noticed that scripts should rebuild the dashboard before start of final server. I believe that scripts/run_dev.js implements this behaviour.
=> fxa-oauth-console requires rebuild of web interface before server starts

.travis.yml, _scripts/install_all.sh
Fixes https://github.com/mozilla/fxa-auth-server/issues/1502; @shane-tomlinson r?
=> fix(install): Generate VAPID keys during auth-server install.

servers.json
Force on *.mozilla.com, and block.*@restmail.net addresses
This enables all of the content server functional tests related to signin unblock to pass. Without it, the tests that test for signin unblock do not pass because no email addresses are forced.
=> feat(config): Add force signin unblock email config.

servers.json
This is to get the content-server functional tests passing locally again.
@vbudhram or @seanmonstar - r?
=> feat(auth-server): Force signin confirmation for sync.*@restmail.net

_scripts/vagrant_provision.sh
Update the npm version installed by vagrant provisioning to the latest version of 2.x.
All dependencies installation log goes to the file ~/provision.log.
Refactored and improved the provisioning messages.
Lines wrapped at 80.
=> fix(vagrant): update npm version from 2.4 to 2.x

_scripts/syncserver.sh
After the migration to CircleCI 2, the syncserver docker image
now runs gunicorn by default, so we don't need to specify it
explicitly.
Fixes #117
=> fix(syncserver): Update syncserver script for latest docker image.

_scripts/syncserver.sh
https://github.com/mozilla/fxa-local-dev/pull/114 didn't fix my problem (not able to sync after a fresh clone of `fxa-local-dev`).
Running without `--net=host` seems sensible to me since we already pass `host.docker.internal` to the docker image.
=> fix(syncserver): run the syncserver in container network

_scripts/install_all.sh
We are changing which rust version to use for email-service. See https://github.com/mozilla/fxa-email-service/pull/160
r? @vladikoff
=> chore(install): update rust version

_scripts/check_mysql.sh, _scripts/create_mysql.js, _scripts/install_all.sh, _scripts/pushbox.sh, _scripts/pushbox_db.sh, _scripts/syncserver.sh, _scripts/update_all.sh, mysql_servers.json, servers.json
This PR allows running a [pushbox](https://github.com/mozilla-services/pushbox) server alongside all the other FxA services.
In the `mysql_servers.json` pm2 configuration, we use the already existing `mydb` mysql container to store our data, otherwise we spawn a `pushbox_db` container (pushbox doesn't have a memory store).
I've also used my "sigint trap trick" to make `mydb` stop after the user runs `pm2 kill`.
=> Add pushbox server

_scripts/install_all.sh
The OAuth server was not working after cloning `fxa-local-dev` on my new computer.
We used to call `node scripts/gen_keys` in the oauth server's package.json `postinstall` step, which doesn't exist anymore.
=> fix(install): generate oauth server keys

_scripts/install_all.sh
We already do this in update_all.sh to avoid updates to package.json,
updating install_all.sh to act the same.
=> chore(install): Use `npm ci` in install_all.sh to avoid updates to package.json
